const translations = {
  en: {
    "nav.home":"Home","nav.story":"Our Story","nav.services":"What We Do","nav.why":"Why Bing&Go","nav.borders":"Across Borders","nav.contact":"Contact",
    "hero.eyebrow":"BING&GO · CROSS-BORDER SERVICES","hero.line1":"Two Worlds.","hero.line2":"One Story.","hero.lead":"Connecting China and the Americas","hero.detail":"10+ years of cross-cultural experience<br>in travel, business, and beyond.","hero.services":"Our Services","hero.connect":"Let's Connect",
    "story.label":"OUR STORY","story.title1":"Bridging Cultures.","story.title2":"Creating Opportunities.","story.p1":"Bing&Go helps make meaningful connections between China and the Americas easier, more practical, and more personal.","story.p2":"With more than a decade of cross-cultural experience, we help people and organizations move confidently across borders — combining local knowledge with on-the-ground execution.","story.p3":"From a private journey to a market-entry project, we turn unfamiliar places and complex cross-border needs into clear, connected experiences.",
    "services.label":"WHAT WE DO","services.travel.title":"Travel & Experiences","services.travel.text":"Customized journeys across China and the Americas — private travel, cultural experiences, group trips, educational programs, and specialized itineraries.","services.business.title":"Business Services","services.business.text":"Meetings, conventions, site visits, logistics, coordination, and local on-the-ground support for companies traveling across borders.","services.market.title":"Market Access & Representation","services.market.text":"Local representation, market exploration, introductions, trade-show support, and project-based presence — without building a full local team.","services.advisory.title":"Cross-Border Advisory","services.advisory.text":"Cross-cultural communication, research, strategy, partnerships, and practical local insight for organizations working between China and the Americas.",
    "why.label":"WHY BING&GO","why.title":"Your local presence, without the overhead.","why.p1.title":"Local Knowledge","why.p1.text":"Deep understanding of China and the Americas.","why.p2.title":"Cross-Cultural Fluency","why.p2.text":"Bilingual, bicultural perspective with real-world experience.","why.p3.title":"Flexible Project Support","why.p3.text":"Agile solutions tailored to your goals and resources.","why.p4.title":"Trusted Connections","why.p4.text":"Strong networks that open doors and create opportunities.",
    "borders.label":"ACROSS BORDERS","borders.c2a.title":"China → Americas","borders.c2a.text":"Building bridges. Creating value.","borders.a2c.title":"Americas → China","borders.a2c.text":"Connecting opportunities. Achieving growth.","borders.learn":"Learn More",
    "contact.title":"Let's Build Something Great Together","contact.text":"We'd love to hear from you.","contact.button":"Contact Us",
    "detail.see":"See Examples","detail.help":"HOW WE CAN HELP","detail.scenarios":"EXAMPLE SCENARIOS","detail.process":"HOW IT WORKS","detail.process.title":"Simple when it needs to be.<br><em>Flexible when it matters.</em>","detail.step1.title":"Tell us the goal","detail.step1.text":"Share what you are trying to accomplish, the timing, location, and any constraints.","detail.step2.title":"We build the scope","detail.step2.text":"We define a practical project plan, deliverables, local support, and communication structure.","detail.step3.title":"We act locally","detail.step3.text":"Bing&Go coordinates and executes the agreed work on the ground.","detail.step4.title":"You stay informed","detail.step4.text":"Your team receives updates, findings, next steps, and follow-through without unnecessary overhead.","detail.model":"WHY THIS MODEL WORKS","detail.cta.label":"START A CONVERSATION","detail.back":"← Back to Across Borders",
    "c2a.breadcrumb":"ACROSS BORDERS · CHINA → AMERICAS","c2a.hero.title":"Your presence in the Americas.<br>Without building a local team.","c2a.hero.text":"From a single convention or business trip to an extended market-entry project, Bing&Go provides flexible, project-based local support for organizations exploring opportunities across the Americas.","c2a.hero.cta":"Discuss Your Project","c2a.intro.title":"Local execution.<br><em>Cross-border perspective.</em>","c2a.intro.p1":"Expanding into a new market does not always require a new office, a full-time hire, or repeated international travel. Sometimes you need trusted people on the ground who can move a project forward.","c2a.intro.p2":"Bing&Go can support a defined project, a specific trip, or an exploratory phase — helping your team gather information, coordinate locally, attend events, connect with relevant organizations, and follow through after the meeting ends.","c2a.s1.title":"Business Trip & Convention Support","c2a.s1.text":"Planning, local logistics, meeting coordination, event support, interpretation coordination, site visits, and post-trip follow-up for teams traveling from China.","c2a.s2.title":"Local Business Representation","c2a.s2.text":"Project-based local presence for meetings, trade shows, site visits, partner communication, and agreed representation when your own team cannot be there.","c2a.s3.title":"Market Exploration","c2a.s3.text":"Initial market research, local observations, competitor and channel exploration, and practical feedback before committing to a larger investment.","c2a.s4.title":"Partner & Supplier Coordination","c2a.s4.text":"Help identifying relevant organizations, arranging introductions, coordinating meetings, conducting local visits, and keeping communication moving across time zones.","c2a.s5.title":"Customized U.S. & Americas Programs","c2a.s5.text":"Purpose-built itineraries for executive teams, institutions, educational groups, business delegations, and clients combining business with cultural experiences.","c2a.s6.title":"On-the-Ground Project Support","c2a.s6.text":"A flexible local resource for time-sensitive tasks, research, site checks, vendor coordination, meeting attendance, and project follow-through.","c2a.m1.title":"No local office required","c2a.m1.text":"Explore opportunities before committing to permanent infrastructure.","c2a.m2.title":"No full-time team required","c2a.m2.text":"Use project-based support when and where you need it.","c2a.m3.title":"Less international travel","c2a.m3.text":"Handle appropriate local tasks without flying your team across the Pacific every time.","c2a.m4.title":"Cross-cultural context","c2a.m4.text":"Reduce friction by working with people who understand both sides of the relationship.","c2a.cta.title":"Planning something in the Americas?","c2a.cta.text":"Tell us what you need, even if the project is still early. We can help turn it into a practical next step.",
    "a2c.breadcrumb":"ACROSS BORDERS · AMERICAS → CHINA","a2c.hero.title":"Navigate China with<br>local context and support.","a2c.hero.text":"For companies, institutions, teams, and travelers from the Americas, Bing&Go helps make China more accessible — from business visits and market exploration to local coordination and cross-cultural support.","a2c.hero.cta":"Discuss Your Project","a2c.intro.title":"Understand the market.<br><em>Navigate the culture.</em>","a2c.intro.p1":"China can offer extraordinary opportunities, but unfamiliar logistics, language, business practices, and cultural context can make even a simple visit harder than it needs to be.","a2c.intro.p2":"Bing&Go provides practical, flexible support before, during, and after your project — helping you plan visits, coordinate locally, explore the market, communicate effectively, and make better-informed decisions.","a2c.s1.title":"China Market Exploration","a2c.s1.text":"Early-stage research, local observations, market visits, competitor context, and practical orientation before committing significant resources.","a2c.s2.title":"Business Travel to China","a2c.s2.text":"Customized business itineraries, local transportation, meeting coordination, cultural context, interpretation coordination, and on-the-ground support.","a2c.s3.title":"Supplier & Partner Visits","a2c.s3.text":"Coordinate site visits, meetings, local travel, and follow-up so your team can focus on evaluating the relationship and opportunity.","a2c.s4.title":"Local Coordination","a2c.s4.text":"A local point of coordination for vendors, meetings, schedules, events, logistics, and project communication across time zones.","a2c.s5.title":"Cross-Cultural Communication","a2c.s5.text":"Practical guidance on communication styles, expectations, meeting dynamics, relationship-building, and cultural context.","a2c.s6.title":"Customized China Experiences","a2c.s6.text":"Private, executive, institutional, educational, and cultural programs designed around the purpose of your visit rather than a standard tour package.","a2c.m1.title":"Local context from the start","a2c.m1.text":"Build a clearer plan before arriving rather than learning everything after you land.","a2c.m2.title":"One point of coordination","a2c.m2.text":"Reduce complexity by consolidating local logistics, communication, and project support.","a2c.m3.title":"Flexible scope","a2c.m3.text":"Use only the support your project requires, from a single visit to a longer engagement.","a2c.m4.title":"Cross-cultural fluency","a2c.m4.text":"Navigate practical and cultural differences with a perspective that understands both sides.","a2c.cta.title":"Planning something in China?","a2c.cta.text":"Tell us where you want to go and what you are trying to accomplish. We can help build the right support around it."
  },
  zh: {
    "nav.home":"首页","nav.story":"我们的故事","nav.services":"服务领域","nav.why":"为什么选择 Bing&Go","nav.borders":"跨境服务","nav.contact":"联系我们",
    "hero.eyebrow":"BING&GO · 跨境服务","hero.line1":"两个世界。","hero.line2":"一个故事。","hero.lead":"连接中国与美洲","hero.detail":"十余年跨文化经验<br>覆盖旅行、商务与更多领域。","hero.services":"我们的服务","hero.connect":"联系我们",
    "story.label":"我们的故事","story.title1":"跨越文化。","story.title2":"创造机会。","story.p1":"Bing&Go 致力于让中国与美洲之间的连接更简单、更务实，也更具温度。","story.p2":"凭借十余年的跨文化经验，我们帮助个人、企业和机构更从容地跨越边界，将本地知识与实际执行能力结合起来。","story.p3":"从私人定制旅行到市场进入项目，我们把陌生环境和复杂的跨境需求，转化为清晰、可靠、可执行的方案。",
    "services.label":"我们做什么","services.travel.title":"旅行与体验","services.travel.text":"定制中国与美洲之间的旅行体验，包括私人旅行、文化体验、团体项目、教育行程及特色定制路线。","services.business.title":"商务服务","services.business.text":"为跨境企业提供会议、展会、考察、行程协调、物流及当地落地支持。","services.market.title":"市场拓展与商业代表","services.market.text":"提供当地代表、市场考察、资源引荐、展会支持及项目制落地服务，无需先建立完整海外团队。","services.advisory.title":"跨境顾问","services.advisory.text":"提供跨文化沟通、市场研究、战略、合作伙伴拓展以及中国与美洲之间的本地商业洞察。",
    "why.label":"为什么选择 BING&GO","why.title":"拥有当地支持，无需承担建立团队的成本。","why.p1.title":"本地知识","why.p1.text":"深入理解中国与美洲市场和文化。","why.p2.title":"跨文化能力","why.p2.text":"双语、跨文化视角与真实项目经验。","why.p3.title":"灵活项目支持","why.p3.text":"根据目标、时间与资源灵活配置支持。","why.p4.title":"可靠资源连接","why.p4.text":"以可信赖的网络帮助打开机会之门。",
    "borders.label":"跨越边界","borders.c2a.title":"中国 → 美洲","borders.c2a.text":"搭建桥梁，创造价值。","borders.a2c.title":"美洲 → 中国","borders.a2c.text":"连接机会，实现增长。","borders.learn":"了解更多",
    "contact.title":"一起创造更大的可能","contact.text":"欢迎告诉我们你的想法。","contact.button":"联系我们",
    "detail.see":"查看示例","detail.help":"我们可以如何协助","detail.scenarios":"应用场景示例","detail.process":"合作方式","detail.process.title":"需要简单时保持简单。<br><em>需要灵活时足够灵活。</em>","detail.step1.title":"告诉我们目标","detail.step1.text":"说明你想完成什么、时间、地点以及主要限制条件。","detail.step2.title":"我们制定范围","detail.step2.text":"共同确定项目计划、交付内容、当地支持和沟通方式。","detail.step3.title":"我们在当地执行","detail.step3.text":"Bing&Go 按约定在当地协调并推进具体工作。","detail.step4.title":"你始终掌握进展","detail.step4.text":"你的团队持续获得进展、发现、下一步建议和后续结果，无需承担不必要的固定成本。","detail.model":"为什么这种模式有效","detail.cta.label":"开启对话","detail.back":"← 返回跨境服务",
    "c2a.breadcrumb":"跨境服务 · 中国 → 美洲","c2a.hero.title":"在美洲拥有当地支持。<br>无需先建立完整团队。","c2a.hero.text":"从一次展会或商务出行，到持续数月的市场进入项目，Bing&Go 为探索美洲机会的企业和机构提供灵活、项目制的当地支持。","c2a.hero.cta":"讨论你的项目","c2a.intro.title":"当地执行。<br><em>跨境视角。</em>","c2a.intro.p1":"进入新市场并不一定意味着马上设立办公室、招聘全职员工，或让团队频繁跨洋出差。有时真正需要的是值得信赖的当地力量，把项目向前推进。","c2a.intro.p2":"Bing&Go 可以支持一个明确项目、一次商务出行或前期探索阶段，帮助团队收集信息、当地协调、参加活动、连接相关机构，并做好会后的持续跟进。","c2a.s1.title":"商务出行与展会支持","c2a.s1.text":"为来自中国的团队提供行程规划、当地物流、会议协调、展会支持、口译协调、现场考察和会后跟进。","c2a.s2.title":"当地商业代表","c2a.s2.text":"在你的团队无法亲自到场时，按约定范围提供会议、展会、现场考察、合作伙伴沟通及项目制当地代表支持。","c2a.s3.title":"市场探索","c2a.s3.text":"在投入更大资源前，通过初步市场研究、当地观察、竞争与渠道探索以及务实反馈，帮助判断机会。","c2a.s4.title":"合作伙伴与供应商协调","c2a.s4.text":"协助寻找相关机构、安排引荐和会议、进行当地拜访，并让跨时区沟通持续推进。","c2a.s5.title":"定制美国与美洲项目","c2a.s5.text":"为企业高管、机构、教育团体、商务代表团及希望结合商务与文化体验的客户设计专属行程。","c2a.s6.title":"当地项目支持","c2a.s6.text":"针对时效性任务、研究、现场核实、供应商协调、会议参加和项目跟进提供灵活当地资源。","c2a.m1.title":"无需先设当地办公室","c2a.m1.text":"在投入长期固定成本前先探索和验证机会。","c2a.m2.title":"无需先组建全职团队","c2a.m2.text":"只在需要的时间和地点使用项目制支持。","c2a.m3.title":"减少跨洋出差","c2a.m3.text":"适合当地处理的任务，不必每一次都让整个团队飞越太平洋。","c2a.m4.title":"跨文化语境","c2a.m4.text":"通过理解双方文化和沟通方式的人降低合作摩擦。","c2a.cta.title":"正在规划美洲项目？","c2a.cta.text":"即使项目还处于早期，也可以告诉我们你的需求。我们可以一起把它变成可执行的下一步。",
    "a2c.breadcrumb":"跨境服务 · 美洲 → 中国","a2c.hero.title":"用本地视角与支持，<br>更从容地走进中国。","a2c.hero.text":"面向来自美洲的企业、机构、团队和旅行者，Bing&Go 帮助中国变得更容易理解和进入——从商务拜访、市场探索到当地协调与跨文化支持。","a2c.hero.cta":"讨论你的项目","a2c.intro.title":"理解市场。<br><em>读懂文化。</em>","a2c.intro.p1":"中国拥有大量机会，但陌生的物流、语言、商业习惯和文化语境，也会让一次看似简单的访问变得复杂。","a2c.intro.p2":"Bing&Go 在项目之前、期间和之后提供务实灵活的支持，帮助你规划拜访、当地协调、探索市场、有效沟通并做出更充分的信息判断。","a2c.s1.title":"中国市场探索","a2c.s1.text":"通过早期研究、当地观察、市场拜访、竞争环境和实际业务语境，在投入大量资源前建立基本判断。","a2c.s2.title":"中国商务出行","a2c.s2.text":"提供定制商务行程、当地交通、会议协调、文化背景、口译协调和落地支持。","a2c.s3.title":"供应商与合作伙伴拜访","a2c.s3.text":"协助协调现场拜访、会议、当地交通和后续跟进，让团队专注于评估合作关系和机会。","a2c.s4.title":"当地协调","a2c.s4.text":"作为当地协调点，支持供应商、会议、日程、活动、物流和跨时区项目沟通。","a2c.s5.title":"跨文化沟通","a2c.s5.text":"针对沟通方式、预期、会议互动、关系建立和文化语境提供务实指导。","a2c.s6.title":"定制中国体验","a2c.s6.text":"面向私人、高管、机构、教育和文化项目，根据访问目的设计，而不是套用标准旅行团路线。","a2c.m1.title":"从一开始就有本地语境","a2c.m1.text":"在出发前建立更清晰的计划，而不是落地后才开始摸索。","a2c.m2.title":"一个当地协调窗口","a2c.m2.text":"整合当地物流、沟通与项目支持，减少复杂度。","a2c.m3.title":"灵活的合作范围","a2c.m3.text":"从一次拜访到较长期项目，只使用真正需要的支持。","a2c.m4.title":"跨文化理解","a2c.m4.text":"以理解双方语境的视角处理实际和文化差异。","a2c.cta.title":"正在规划中国项目？","a2c.cta.text":"告诉我们你想去哪里、希望完成什么。我们可以围绕目标设计合适的支持方案。"
  },
  es: {
    "nav.home":"Inicio","nav.story":"Nuestra historia","nav.services":"Servicios","nav.why":"Por qué Bing&Go","nav.borders":"Entre fronteras","nav.contact":"Contacto",
    "hero.eyebrow":"BING&GO · SERVICIOS TRANSFRONTERIZOS","hero.line1":"Dos mundos.","hero.line2":"Una historia.","hero.lead":"Conectando China y las Américas","hero.detail":"Más de 10 años de experiencia intercultural<br>en viajes, negocios y mucho más.","hero.services":"Nuestros servicios","hero.connect":"Conectemos",
    "story.label":"NUESTRA HISTORIA","story.title1":"Uniendo culturas.","story.title2":"Creando oportunidades.","story.p1":"Bing&Go facilita conexiones significativas entre China y las Américas de una forma más sencilla, práctica y humana.","story.p2":"Con más de una década de experiencia intercultural, ayudamos a personas, empresas y organizaciones a moverse entre fronteras con mayor confianza, combinando conocimiento local y ejecución sobre el terreno.","story.p3":"Desde un viaje privado hasta un proyecto de entrada al mercado, convertimos entornos desconocidos y necesidades transfronterizas complejas en experiencias claras y conectadas.",
    "services.label":"QUÉ HACEMOS","services.travel.title":"Viajes y experiencias","services.travel.text":"Viajes personalizados por China y las Américas: experiencias privadas y culturales, grupos, programas educativos e itinerarios especializados.","services.business.title":"Servicios empresariales","services.business.text":"Reuniones, convenciones, visitas, logística, coordinación y apoyo local para empresas que trabajan entre mercados.","services.market.title":"Acceso al mercado y representación","services.market.text":"Representación local, exploración de mercados, presentaciones, ferias y presencia por proyecto, sin necesidad de crear un equipo local completo.","services.advisory.title":"Asesoría transfronteriza","services.advisory.text":"Comunicación intercultural, investigación, estrategia, alianzas y conocimiento local para organizaciones que trabajan entre China y las Américas.",
    "why.label":"POR QUÉ BING&GO","why.title":"Tu presencia local, sin los costes de crear un equipo.","why.p1.title":"Conocimiento local","why.p1.text":"Comprensión profunda de China y las Américas.","why.p2.title":"Experiencia intercultural","why.p2.text":"Perspectiva bilingüe y bicultural con experiencia real.","why.p3.title":"Apoyo flexible","why.p3.text":"Soluciones ágiles adaptadas a tus objetivos y recursos.","why.p4.title":"Conexiones de confianza","why.p4.text":"Redes sólidas que abren puertas y crean oportunidades.",
    "borders.label":"ENTRE FRONTERAS","borders.c2a.title":"China → Américas","borders.c2a.text":"Construyendo puentes. Creando valor.","borders.a2c.title":"Américas → China","borders.a2c.text":"Conectando oportunidades. Logrando crecimiento.","borders.learn":"Más información",
    "contact.title":"Construyamos algo grande juntos","contact.text":"Nos encantará conocer tu proyecto.","contact.button":"Contáctanos",
    "detail.see":"Ver ejemplos","detail.help":"CÓMO PODEMOS AYUDAR","detail.scenarios":"EJEMPLOS DE ESCENARIOS","detail.process":"CÓMO FUNCIONA","detail.process.title":"Simple cuando debe serlo.<br><em>Flexible cuando importa.</em>","detail.step1.title":"Cuéntanos el objetivo","detail.step1.text":"Comparte qué quieres lograr, el calendario, el lugar y las principales limitaciones.","detail.step2.title":"Definimos el alcance","detail.step2.text":"Creamos un plan práctico, entregables, apoyo local y una estructura de comunicación.","detail.step3.title":"Actuamos localmente","detail.step3.text":"Bing&Go coordina y ejecuta el trabajo acordado sobre el terreno.","detail.step4.title":"Te mantenemos informado","detail.step4.text":"Tu equipo recibe actualizaciones, hallazgos, próximos pasos y seguimiento sin costes innecesarios.","detail.model":"POR QUÉ FUNCIONA ESTE MODELO","detail.cta.label":"INICIAR UNA CONVERSACIÓN","detail.back":"← Volver a Entre fronteras",
    "c2a.breadcrumb":"ENTRE FRONTERAS · CHINA → AMÉRICAS","c2a.hero.title":"Tu presencia en las Américas.<br>Sin crear un equipo local.","c2a.hero.text":"Desde una convención o viaje de negocios hasta un proyecto prolongado de entrada al mercado, Bing&Go ofrece apoyo local flexible y por proyecto para organizaciones que exploran oportunidades en las Américas.","c2a.hero.cta":"Hablemos de tu proyecto","c2a.intro.title":"Ejecución local.<br><em>Perspectiva transfronteriza.</em>","c2a.intro.p1":"Entrar en un nuevo mercado no siempre requiere abrir una oficina, contratar personal a tiempo completo o viajar internacionalmente de forma constante. A veces necesitas personas de confianza sobre el terreno.","c2a.intro.p2":"Bing&Go puede apoyar un proyecto concreto, un viaje específico o una fase exploratoria, ayudando a recopilar información, coordinar localmente, asistir a eventos, conectar con organizaciones relevantes y dar seguimiento.","c2a.s1.title":"Viajes de negocios y convenciones","c2a.s1.text":"Planificación, logística local, coordinación de reuniones, apoyo en eventos, interpretación, visitas y seguimiento para equipos que viajan desde China.","c2a.s2.title":"Representación empresarial local","c2a.s2.text":"Presencia local por proyecto para reuniones, ferias, visitas, comunicación con socios y representación acordada cuando tu equipo no puede estar allí.","c2a.s3.title":"Exploración de mercado","c2a.s3.text":"Investigación inicial, observaciones locales, competencia, canales y feedback práctico antes de realizar una inversión mayor.","c2a.s4.title":"Coordinación de socios y proveedores","c2a.s4.text":"Apoyo para identificar organizaciones, organizar presentaciones y reuniones, realizar visitas y mantener la comunicación entre husos horarios.","c2a.s5.title":"Programas personalizados en EE.UU. y las Américas","c2a.s5.text":"Itinerarios diseñados para ejecutivos, instituciones, grupos educativos y delegaciones empresariales que combinan negocios y experiencias culturales.","c2a.s6.title":"Apoyo local de proyectos","c2a.s6.text":"Un recurso local flexible para tareas urgentes, investigación, verificaciones, proveedores, reuniones y seguimiento de proyectos.","c2a.m1.title":"Sin oficina local","c2a.m1.text":"Explora oportunidades antes de comprometerte con infraestructura permanente.","c2a.m2.title":"Sin equipo a tiempo completo","c2a.m2.text":"Utiliza apoyo por proyecto cuando y donde lo necesites.","c2a.m3.title":"Menos viajes internacionales","c2a.m3.text":"Resuelve tareas locales apropiadas sin enviar a tu equipo a cruzar el Pacífico cada vez.","c2a.m4.title":"Contexto intercultural","c2a.m4.text":"Reduce fricciones trabajando con personas que entienden ambos lados de la relación.","c2a.cta.title":"¿Planeas algo en las Américas?","c2a.cta.text":"Cuéntanos qué necesitas, incluso si el proyecto está en una fase temprana. Podemos ayudarte a convertirlo en el siguiente paso.",
    "a2c.breadcrumb":"ENTRE FRONTERAS · AMÉRICAS → CHINA","a2c.hero.title":"Navega China con<br>contexto y apoyo local.","a2c.hero.text":"Para empresas, instituciones, equipos y viajeros de las Américas, Bing&Go hace que China sea más accesible: desde visitas de negocios y exploración de mercado hasta coordinación local y apoyo intercultural.","a2c.hero.cta":"Hablemos de tu proyecto","a2c.intro.title":"Comprende el mercado.<br><em>Navega la cultura.</em>","a2c.intro.p1":"China ofrece oportunidades extraordinarias, pero la logística, el idioma, las prácticas empresariales y el contexto cultural pueden complicar incluso una visita sencilla.","a2c.intro.p2":"Bing&Go ofrece apoyo práctico y flexible antes, durante y después del proyecto para planificar visitas, coordinar localmente, explorar el mercado, comunicarte mejor y tomar decisiones informadas.","a2c.s1.title":"Exploración del mercado chino","a2c.s1.text":"Investigación inicial, observaciones locales, visitas de mercado, competencia y orientación práctica antes de comprometer recursos importantes.","a2c.s2.title":"Viajes de negocios a China","a2c.s2.text":"Itinerarios personalizados, transporte local, coordinación de reuniones, contexto cultural, interpretación y apoyo sobre el terreno.","a2c.s3.title":"Visitas a proveedores y socios","a2c.s3.text":"Coordinación de visitas, reuniones, transporte y seguimiento para que tu equipo se concentre en evaluar la relación y la oportunidad.","a2c.s4.title":"Coordinación local","a2c.s4.text":"Un punto local para coordinar proveedores, reuniones, horarios, eventos, logística y comunicación de proyectos.","a2c.s5.title":"Comunicación intercultural","a2c.s5.text":"Orientación práctica sobre estilos de comunicación, expectativas, reuniones, relaciones y contexto cultural.","a2c.s6.title":"Experiencias personalizadas en China","a2c.s6.text":"Programas privados, ejecutivos, institucionales, educativos y culturales diseñados alrededor del propósito de la visita.","a2c.m1.title":"Contexto local desde el inicio","a2c.m1.text":"Construye un plan más claro antes de llegar, en lugar de aprenderlo todo después.","a2c.m2.title":"Un punto de coordinación","a2c.m2.text":"Reduce la complejidad consolidando logística, comunicación y apoyo local.","a2c.m3.title":"Alcance flexible","a2c.m3.text":"Utiliza solo el apoyo que requiere tu proyecto, desde una visita hasta una colaboración más larga.","a2c.m4.title":"Fluidez intercultural","a2c.m4.text":"Navega diferencias prácticas y culturales con una perspectiva que entiende ambos lados.","a2c.cta.title":"¿Planeas algo en China?","a2c.cta.text":"Cuéntanos adónde quieres ir y qué quieres lograr. Podemos ayudarte a crear el apoyo adecuado."
  }
};

function setLanguage(lang){
  const dict = translations[lang] || translations.en;
  document.documentElement.lang = lang === "zh" ? "zh-CN" : lang;
  document.querySelectorAll("[data-i18n]").forEach(el=>{
    const value = dict[el.dataset.i18n];
    if(value !== undefined) el.innerHTML = value;
  });
  document.querySelectorAll(".lang").forEach(btn=>{
    btn.classList.toggle("active", btn.dataset.lang === lang);
  });
  localStorage.setItem("bingandgo-language",lang);
}
document.querySelectorAll(".lang").forEach(btn=>{
  btn.addEventListener("click",()=>setLanguage(btn.dataset.lang));
});
setLanguage(localStorage.getItem("bingandgo-language") || "en");

const menuToggle=document.getElementById("menuToggle");
const mainNav=document.getElementById("mainNav");
if(menuToggle && mainNav){
  menuToggle.addEventListener("click",()=>mainNav.classList.toggle("open"));
  mainNav.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>mainNav.classList.remove("open")));
}
